# Generated by Django 3.1 on 2021-02-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210202_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
